### ISSUE TITLE
i download your source code, and run command "electron .", but show a blank window.( in windows os)

### ISSUE THREAD

**Issue by Carbs0126** [FlorianFe/Elements#1]

**Comment by Carbs0126** [comment]
could you tell me how to run your source code?

**Comment by FlorianFe** [comment]
At first you need to install git and bower globally. When its done you need the commands

"npm install" and
"bower install"

to install all dependencies. After the installation finished you can use "npm start" or "electron ." to start the app. 

I will add this steps to the README :)

**Comment by Carbs0126** [comment]
not very clear but i will try. thank you.

**Comment by blakeearth** [comment]
Will your everyday users have to do this as well?

**Comment by Carbs0126** [comment]
hi blakeearth ，sorry not clear about what you said. i have done as readme, and now works well

**Comment by FlorianFe** [comment]
@blakeearth users who just want to use the app don't need to do this. They can just download the release version. Only users who want to change something in the code need to follow this steps 😊

**Comment by blakeearth** [comment]
Okay, apologies. Very nice app!

**Comment by FlorianFe** [comment]
No need to apologise :) and thanks!

**Comment by Carbs0126** [comment]
is electron able to setup a suspention window? such as a little square window on top of all windows to show downloading progress. usually used by some download softwares

**Comment by FlorianFe** [comment]
Can you give me an example?

**Comment by Carbs0126** [comment]
![suspension_window](https://user-images.githubusercontent.com/14228871/27990802-f7bdeb4a-6494-11e7-84a5-cfafb5ef1091.png)

**Comment by Carbs0126** [comment]
i am using web browser, while downloading some file, the blue rectangle window can always 'float' on the top of other software( such a web browser, text editors...), can electron build a window like this?

**Comment by FlorianFe** [comment]
I'm not sure if I understood you completely, but I think it should be possible as [Frameless Window](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md).

**Comment by Carbs0126** [comment]
thank you so much
