### ISSUE TITLE
Linux Version - App Image

### ISSUE THREAD

**Issue by stelad000** [FlorianFe/Elements#4]
Maybe a linux version?

**Comment by FlorianFe** [comment]
Building an App Image doesn't work correctly for some reason. 
But I added a .deb file download for Linux Users =)

**Comment by probonopd** [comment]
Presumably an [AppImage](https://appimage.org/) is meant. What is the issue @FlorianFe? Can I help?

**Comment by FlorianFe** [comment]
I just updated the npm dependencies and it seem to work now 🤔
However you can download it on the main and release page now =)

**Comment by probonopd** [comment]
Thanks for merging. Please ping me once a release containing this fix is available for download so that I can re-test.
